name: build

on:
  push:
    branches:
      - main
  pull_request:
  create:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: kuroun/remote_entity/.github/actions/ruby_build@main
