name: build

on:
  push:
    branches:
      - main

  pull_request:
  create:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    strategy:
      matrix:
        ruby:
          - '3.2.2'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Install dependencies
      run: bundle install
    - name: Run rubocop
      run: bundle exec rubocop .
    - name: Run tests
      run: bundle exec rspec

