name: Release

on:
  release:
    types: [created]

jobs:
  release:
    if: github.actor == 'kuroun'
    runs-on: ubuntu-latest
    name: Release
    steps:
    - uses: kseung-gpsw/remote_entity/.github/actions/ruby_build@main
    - name: Build and publish gem
      run: |
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
