name: Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
    - uses: kseung-gpsw/remote_entity/.github/actions/ruby_build@main
    - name: Build and publish gem
      run: |
        gem build *.gemspec
        gem push *.gem
      env:
        RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
